export const products = [
  {
    id: 1,
    name: "iPhone 13 Pro Max",
    image:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-iphone-13-pro-max-silver-2023?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1679072987085",
    description: "The latest iPhone model with advanced features.",
    price: 799.99,
    category: "Electronics",
    brand: "Apple",
    rating: 3.0,
    in_stock: true,
    color: "Midnight Green",
    weight: "0.2 kg",
    dimensions: {
      length: "5.78 inches",
      width: "2.82 inches",
      height: "0.30 inches",
    },
  },
  {
    id: 2,
    name: "MacBook Air",
    image:
      "https://reviewed-com-res.cloudinary.com/image/fetch/s--Q-ZGPp9y--/b_white,c_limit,cs_srgb,f_auto,fl_progressive.strip_profile,g_center,q_auto,w_1200/https://reviewed-production.s3.amazonaws.com/1607081088000/DSC_0877.jpg",
    description: "A sleek and lightweight laptop for productivity.",
    price: 1199.99,
    category: "Electronics",
    brand: "Apple",
    rating: 4.9,
    in_stock: true,
    color: "Silver",
    weight: "1.29 kg",
    dimensions: {
      length: "11.97 inches",
      width: "8.36 inches",
      height: "0.63 inches",
    },
  },
  {
    id: 3,
    name: "Samsung 4K Smart TV",
    image:
      "https://i5.walmartimages.com/seo/SAMSUNG-55-Class-CU7000B-Crystal-UHD-4K-Smart-Television-UN55CU7000BXZA_76061f73-bf65-4f71-934a-c42e5ffa8338.9fd15e6bb578750ebdde8027bfdd3bdc.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
    description: "Experience stunning visuals with this 4K Smart TV.",
    price: 899.99,
    category: "Electronics",
    brand: "Samsung",
    rating: 4.7,
    in_stock: true,
    color: "Black",
    weight: "18.2 kg",
    dimensions: {
      length: "48.4 inches",
      width: "9.9 inches",
      height: "30.4 inches",
    },
  },
  {
    id: 4,
    name: "Levi's Men's Jeans",
    image:
      "https://cdn11.bigcommerce.com/s-cwps3viz1k/images/stencil/2048x2048/products/1534/3599/levi-s-reg-men-s-550-trade-relaxed-fit-jeans-rinsed-indigo-114821__26857.1633365948.jpg?c=1",
    description: "Classic and comfortable jeans for men.",
    price: 59.99,
    category: "Clothing",
    brand: "Levi's",
    rating: 4.6,
    in_stock: true,
    color: "Blue",
    weight: "0.8 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 5,
    name: "KitchenAid Stand Mixer",
    image:
      "https://cb.scene7.com/is/image/Crate/KitchenAidArtStMxACAVSSS21_VND/$web_pdp_main_carousel_low$/210323153457/kitchenaid-artisan-series-5-quart-tilt-head-almond-cream-stand-mixer.jpg",
    description: "A versatile kitchen gadget for baking enthusiasts.",
    price: 299.99,
    category: "Kitchen",
    brand: "KitchenAid",
    rating: 4.9,
    in_stock: true,
    color: "Empire Red",
    weight: "11.3 kg",
    dimensions: {
      length: "14.1 inches",
      width: "8.7 inches",
      height: "13.9 inches",
    },
  },
  {
    id: 6,
    name: "Sony Noise-Canceling Headphones",
    image:
      "https://i.pcmag.com/imagery/reviews/05Wp9VPzUM1Lbgv83fxGRCi-1..v1596633627.jpg",
    description:
      "Immerse yourself in high-quality audio with noise-canceling technology.",
    price: 249.99,
    category: "Electronics",
    brand: "Sony",
    rating: 4.5,
    in_stock: true,
    color: "Black",
    weight: "0.24 kg",
    dimensions: {
      length: "7.31 inches",
      width: "2.94 inches",
      height: "9.93 inches",
    },
  },
  {
    id: 7,
    name: "Adidas Running Shoes",
    image:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/cacdfe6bde8d41209e27aef600ebc823_9366/Adizero_SL_Running_Shoes_Turquoise_GV9090_01_standard.jpg",
    description: "Comfortable and durable running shoes for athletes.",
    price: 79.99,
    category: "Footwear",
    brand: "Adidas",
    rating: 4.7,
    in_stock: true,
    color: "White/Blue",
    weight: "0.4 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 8,
    name: "LG UltraWide Monitor",
    image:
      "https://media.us.lg.com/transform/ecomm-PDPGallery-1100x730/13330a64-d09e-499c-b978-0560955f0620/md08003341-DZ-01-jpg",
    description: "A wide and immersive monitor for productivity and gaming.",
    price: 499.99,
    category: "Electronics",
    brand: "LG",
    rating: 4.8,
    in_stock: true,
    color: "Black",
    weight: "7.5 kg",
    dimensions: {
      length: "44.4 inches",
      width: "9.1 inches",
      height: "21.5 inches",
    },
  },
  {
    id: 9,
    name: "Nike Air Max Sneakers",
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9bd1131b-70ca-40c0-8548-208c4d2d0ae8/air-max-correlate-womens-shoes-29Vjp0.png",
    description: "Stylish and comfortable sneakers for everyday wear.",
    price: 129.99,
    category: "Footwear",
    brand: "Nike",
    rating: 4.6,
    in_stock: true,
    color: "Black/Red",
    weight: "0.5 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 10,
    name: "Bose SoundLink Speaker",
    image:
      "https://assets.bosecreative.com/transform/f574ddcc-222b-4dd5-be1f-fa5f0ce781bc/SLF_product-silo_black_bundle_1200x1022",
    description: "Portable Bluetooth speaker with rich sound quality.",
    price: 129.99,
    category: "Electronics",
    brand: "Bose",
    rating: 4.7,
    in_stock: true,
    color: "Silver",
    weight: "0.67 kg",
    dimensions: {
      length: "2.24 inches",
      width: "5.16 inches",
      height: "5.00 inches",
    },
  },
  {
    id: 11,
    name: "Sony 65-Inch 4K OLED TV",
    image:
      "https://i5.walmartimages.com/seo/Sony-65-Class-A80K-4K-HDR-OLED-TV-with-smart-Google-TV-XR65A80K-2022-Model_8fe49423-5e98-44d8-bb07-9ee95ff3b324.a30fc2a8c7088f6dbaacbb50f1e06d2a.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
    description: "Experience breathtaking visuals with this 4K OLED TV.",
    price: 1999.99,
    category: "Electronics",
    brand: "Sony",
    rating: 4.9,
    in_stock: true,
    color: "Black",
    weight: "24.7 kg",
    dimensions: {
      length: "57.0 inches",
      width: "13.9 inches",
      height: "35.0 inches",
    },
  },
  {
    id: 12,
    name: "Calvin Klein Men's Dress Shirt",
    image:
      "https://images.squarespace-cdn.com/content/v1/5377ff01e4b002aab7ad0a7f/1555607108331-2KC9NJUMQI1CHKI64WKH/ck.jpg?format=1500w",
    description: "A stylish dress shirt for formal occasions.",
    price: 69.99,
    category: "Clothing",
    brand: "Calvin Klein",
    rating: 4.5,
    in_stock: true,
    color: "White",
    weight: "0.3 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 13,
    name: "Dell XPS 15 Laptop",
    image:
      "https://s.yimg.com/uu/api/res/1.2/Wz1QqUatkKcwloEucfJouA--~B/aD0xMjE2O3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2022-06/5e8c1f20-e8c7-11ec-bfdf-846a6ce9c468.cf.jpg",
    description: "Powerful laptop for professionals and gamers.",
    price: 1499.99,
    category: "Electronics",
    brand: "Dell",
    rating: 4.8,
    in_stock: true,
    color: "Silver",
    weight: "1.83 kg",
    dimensions: {
      length: "13.57 inches",
      width: "9.06 inches",
      height: "0.66 inches",
    },
  },
  {
    id: 14,
    name: "Nike Women's Running Shoes",
    image:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/959bf54a-d537-43bd-b03e-016f4ae2b945/structure-24-womens-road-running-shoes-2hXmxT.png",
    description: "Comfortable and supportive running shoes for women.",
    price: 89.99,
    category: "Footwear",
    brand: "Nike",
    rating: 4.7,
    in_stock: true,
    color: "Pink/Gray",
    weight: "0.4 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 15,
    name: "Cuisinart 12-Cup Coffee Maker",
    image:
      "https://www.cuisinart.com/globalassets/cuisinart-image-feed/dcc-500/dcc-500.jpg",
    description: "Brew delicious coffee with this 12-cup coffee maker.",
    price: 59.99,
    category: "Kitchen",
    brand: "Cuisinart",
    rating: 0.6,
    in_stock: true,
    color: "Black",
    weight: "3.18 kg",
    dimensions: {
      length: "10.13 inches",
      width: "10.38 inches",
      height: "14.25 inches",
    },
  },
  {
    id: 16,
    name: "Under Armour Men's Hoodie",
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/V5-1370805-035_FC?rp=standard-0pad%7CpdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on%2Con&bgc=F0F0F0&wid=566&hei=708&size=566%2C708",
    description: "A comfortable and warm hoodie for men.",
    price: 49.99,
    category: "Clothing",
    brand: "Under Armour",
    rating: 1.5,
    in_stock: true,
    color: "Gray",
    weight: "0.6 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 17,
    name: "Canon EOS Rebel T7i DSLR Camera",
    image: "https://m.media-amazon.com/images/I/81aoNZFMbkL.jpg",
    description: "Capture stunning photos with this DSLR camera.",
    price: 699.99,
    category: "Electronics",
    brand: "Canon",
    rating: 3.7,
    in_stock: true,
    color: "Black",
    weight: "0.53 kg",
    dimensions: {
      length: "5.16 inches",
      width: "3.94 inches",
      height: "3.03 inches",
    },
  },
  {
    id: 18,
    name: "Puma Men's Running Shoes",
    image: "https://m.media-amazon.com/images/I/51Od2OkIqsL._AC_UY1000_.jpg",
    description: "Durable and comfortable running shoes for men.",
    price: 69.99,
    category: "Footwear",
    brand: "Puma",
    rating: 4.6,
    in_stock: true,
    color: "Black/White",
    weight: "0.4 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
  {
    id: 19,
    name: "Amazon Echo Dot (4th Gen) Smart Speaker",
    image:
      "https://www.pcrichard.com/dw/image/v2/BFXM_PRD/on/demandware.static/-/Sites-pcrichard-master-product-catalog/default/dw633273b0/images/hires/Z_B09B8W5FW7.jpg?sw=800&sh=800&sm=fit",
    description: "Voice-controlled smart speaker for your home.",
    price: 49.99,
    category: "Electronics",
    brand: "Amazon",
    rating: 4.6,
    in_stock: true,
    color: "Charcoal",
    weight: "0.34 kg",
    dimensions: {
      length: "3.89 inches",
      width: "3.89 inches",
      height: "3.50 inches",
    },
  },
  {
    id: 20,
    name: "Nike Women's Yoga Leggings",
    image:
      "https://media.kohlsimg.com/is/image/kohls/3596885?wid=600&hei=600&op_sharpen=1",
    description: "Comfortable and stretchy leggings for yoga and workouts.",
    price: 34.99,
    category: "Clothing",
    brand: "Nike",
    rating: 4.7,
    in_stock: true,
    color: "Black",
    weight: "0.2 kg",
    dimensions: {
      length: "N/A",
      width: "N/A",
      height: "N/A",
    },
  },
];
